# 1.Print 'Hello HCIA'.

In [44]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [45]:
a = 5
b = 26
sum = a + b
print(sum)

31


# 3.Define a list and replicate in three different ways.

In [46]:
import copy
l = [1 , 2 , 3]
#1 method
print(l)
print(l[:])
new_list = l[:]
print(l)
print(new_list)
#2 method
new_list = l
print(new_list)
#3 method
new_list = copy.copy(l)
print(new_list)


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


# 4.Define two lists and merge them together.

In [47]:
l1 = ["Hi","all"]
l2 = ["You","are"]
print(l1 + l2)

['Hi', 'all', 'You', 'are']


# 5. Get the last element of the list and print it.

In [48]:
l = [1 , 3 , 5, 0 ,18]
print(l[-1])

18


# 6.Define a tuple that contains only one element.

In [49]:
l = (1,)

# 7.Define a three-line long string.

In [50]:
print('''"Это
длинная
строка"''')

"Это
длинная
строка"


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [51]:
l = (5,7,3)
for i in l:
    print(i)

5
7
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [52]:
def Mul(a,b):
    result = a * b
    return(result)
print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [53]:
import numpy
l = numpy.zeros((5,5))

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [54]:
import numpy
l = numpy.zeros((4,6))

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [55]:
import numpy
l = numpy.arange(15)
l = l.reshape(3,5)

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [56]:
import numpy
l1 = numpy.arange(9).reshape(3,3)
l2 = numpy.arange(9).reshape(3,3)
l = numpy.multiply(l1,l2)
print(l)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
